# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-06 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_id', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=256)),
                ('date', models.CharField(max_length=32)),
                ('share_url', models.CharField(max_length=256)),
                ('image', models.FileField(upload_to='daily/%Y-%m-%d')),
                ('image_source', models.CharField(max_length=256)),
            ],
        ),
    ]
